# Generated by Django 4.1.3 on 2022-11-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body',
            field=models.ManyToManyField(to='main_app.body'),
        ),
    ]
